package cz.muni.fi.xtovarn.heimdall.client.protocol;

public enum ClientEvent {
	NETTY_TCP_CONNECTED,
	ERROR,
	REQUEST_CONNECT,
	RECEIVED_CONNECTED,
	REQUEST_SUBSCRIBE,
	RECEIVED_ACK,
	REQUEST_UNSUBSCRIBE,
	REQUEST_READY,
	REQUEST_STOP,
	RECEIVED_ACK_FOR_READY
}
